{{- if eq .Values.aodbApi.db.createSecret false }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ default "1h" .Values.aodbApi.externalSecret.secretRefreshInterval }}
  secretStoreRef:
    name: {{ default "gcp-clusterstore" .Values.aodbApi.externalSecret.secretStoreName }}
    kind: {{ default "ClusterSecretStore" .Values.aodbApi.externalSecret.secretStoreKind }}
  target:
    name: {{ .Release.Name }}-db
    creationPolicy: Owner
  data:
    - secretKey: db_user
      remoteRef:
        key: {{ .Values.aodbApi.externalSecret.gcpSecretName }}
        property: db_user
        decodingStrategy: None
    - secretKey: db_password
      remoteRef:
        key: {{ .Values.aodbApi.externalSecret.gcpSecretName }}
        property: db_password
        decodingStrategy: None
    - secretKey: db_name
      remoteRef:
        key: {{ .Values.aodbApi.externalSecret.gcpSecretName }}
        property: db_name
        decodingStrategy: None
{{- end }}
