{{- if ne .Values.aodbApi.db.createSecret false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  db_user: {{ .Values.aodbApi.db.user | default "" | quote }}
  db_password: {{ .Values.aodbApi.db.password | default "" | quote }}
  db_name: {{ .Values.aodbApi.db.name | default "" | quote }}
{{- end }}
