{{- if and .Values.aodbApi.mariadb.enabled (eq .Values.aodbApi.mariadb.createSecret false) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-mariadb-root
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ default "1h" .Values.aodbApi.externalSecret.secretRefreshInterval }}
  secretStoreRef:
    name: {{ default "gcp-clusterstore" .Values.aodbApi.externalSecret.secretStoreName }}
    kind: {{ default "ClusterSecretStore" .Values.aodbApi.externalSecret.secretStoreKind }}
  target:
    name: {{ .Release.Name }}-mariadb-root
    creationPolicy: Owner
  data:
    - secretKey: root-password
      remoteRef:
        key: {{ .Values.aodbApi.externalSecret.gcpSecretName }}
        property: mariadb_root_password
        decodingStrategy: None
    - secretKey: root-user
      remoteRef:
        key: {{ .Values.aodbApi.externalSecret.gcpSecretName }}
        property: mariadb_root_user
        decodingStrategy: None
{{- end }}
