apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-serviceaccount
  namespace: {{ .Release.Namespace }}
{{- with .Values.aodbApi.imagePullSecrets }}
imagePullSecrets:
  {{- range . }}
  - name: {{ . }}
  {{- end }}
{{- end }}
